# Generated by Django 5.2.8 on 2025-12-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMasterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_ciphertext_b64', models.TextField()),
                ('mk_nonce_b64', models.CharField(max_length=128)),
                ('mk_mac_b64', models.CharField(max_length=128)),
                ('mk_salt_b64', models.CharField(max_length=128)),
                ('mk_algo', models.CharField(default='xchacha20-poly1305+pbkdf2-sha256', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
