# Generated by Django 5.2.8 on 2026-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='tier',
            field=models.CharField(choices=[('free', 'Free (1GB)'), ('pro', 'Pro (100GB)'), ('enterprise', 'Enterprise (1TB)')], default='free', max_length=20),
        ),
    ]
