# Generated by Django 5.2.8 on 2025-12-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermasterkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_master_key_hex', models.TextField()),
                ('kdf_salt_b64', models.CharField(max_length=255)),
                ('kdf_algorithm', models.CharField(default='pbkdf2-hmac-sha256', max_length=32)),
                ('kdf_iterations', models.IntegerField(default=150000)),
                ('aead_algorithm', models.CharField(default='xchacha20-poly1305', max_length=32)),
                ('nonce_b64', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_blob', models.TextField(blank=True, help_text='Reserved for future encrypted recovery bundle.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserMasterKey',
        ),
    ]
