# Generated by Django 5.2.8 on 2026-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userquota_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='enc_master_key_recovery',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='enc_master_key_recovery_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='recovery_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='recovery_kdf_iterations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='recovery_kdf_memory_kb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='recovery_kdf_parallelism',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterkeyenvelope',
            name='recovery_kdf_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
