# Generated by Django 5.2.8 on 2025-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masterkey_delete_usermasterkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='recovery_blob',
            field=models.TextField(blank=True, help_text='Reserved for future recovery bundle.', null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
