# Generated by Django 5.2.8 on 2025-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_masterkey_recovery_blob_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='recovery_blob',
            field=models.TextField(blank=True, help_text='Reserved for future encrypted recovery bundle.', null=True),
        ),
    ]
