# Generated by Django 5.0.4 on 2026-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
