# Generated by Django 5.2.8 on 2025-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_masterkey_recovery_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='encrypted_master_key_hex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='kdf_salt_b64',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='nonce_b64',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='recovery_blob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
