# Generated by Django 5.0.4 on 2026-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_ends_at',
            field=models.DateTimeField(blank=True, help_text='Downgrade to Free happens after this (7 days post-cancellation).', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purge_at',
            field=models.DateTimeField(blank=True, help_text='Files still over the Free limit get deleted after this (30 days post-cancellation).', null=True),
        ),
    ]
