# Generated by Django 5.0.4 on 2026-08-20 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_last_payment_failed_notified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free (1GB)'), ('pro', 'Pro (100GB)'), ('enterprise', 'Enterprise (1TB)')], max_length=20)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('play_product_id', models.CharField(help_text='e.g. silvora_pro', max_length=100)),
                ('play_base_plan_id', models.CharField(help_text='e.g. pro-monthly', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayBillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_token', models.CharField(max_length=500, unique=True)),
                ('linked_purchase_token', models.CharField(blank=True, max_length=500, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='SUBSCRIPTION_STATE_UNSPECIFIED', max_length=40)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, help_text='Downgrade to Free happens after this (7 days post-expiry).', null=True)),
                ('purge_at', models.DateTimeField(blank=True, help_text='Files still over the Free limit get deleted after this (30 days post-expiry).', null=True)),
                ('last_payment_issue_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='playbillingplan',
            constraint=models.UniqueConstraint(fields=('play_product_id', 'play_base_plan_id'), name='unique_play_product_base_plan'),
        ),
        migrations.AlterUniqueTogether(
            name='playbillingplan',
            unique_together={('tier', 'interval')},
        ),
        migrations.AddField(
            model_name='playbillingsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.playbillingplan'),
        ),
        migrations.AddField(
            model_name='playbillingsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
