# Generated by Django 5.2.8 on 2026-02-26 04:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tenant_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORG', 'Organization')], default='INDIVIDUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_bytes', models.BigIntegerField(default=0)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='tenants.tenant')),
            ],
        ),
    ]
