# Generated by Django 5.2.8 on 2026-02-20 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tenant_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORG', 'Organization'), ('WHITELABEL', 'White Label')], default='INDIVIDUAL', max_length=20)),
                ('device_limit_per_user', models.IntegerField(default=3)),
                ('device_limit_per_tenant', models.IntegerField(default=0)),
                ('storage_limit_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
