# Generated by Django 5.2.9 on 2026-09-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_used', models.CharField(choices=[('0', '0 days'), ('1-2', '1-2 days'), ('3-5', '3-5 days'), ('6+', '6+ days')], max_length=3)),
                ('used_uploading', models.BooleanField(default=False)),
                ('used_downloading', models.BooleanField(default=False)),
                ('used_recovery_phrase', models.BooleanField(default=False)),
                ('used_just_looking', models.BooleanField(default=False)),
                ('used_other', models.CharField(blank=True, max_length=200)),
                ('problems', models.TextField(blank=True)),
                ('confusing', models.TextField(blank=True)),
                ('would_keep_using', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('other_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
