# billing/models.py
from django.conf import settings
from django.db import models

from users.models import SubscriptionTier


class RazorpayPlan(models.Model):
    """
    Config, not a log — maps a (tier, interval) pair to the plan_id Razorpay
    assigns when the plan is created in their dashboard. Razorpay generates
    the plan_id; it can't be invented locally, so these rows are entered by
    hand via Django admin after creating the matching plan on Razorpay's side
    (same shape as Rasova's PaymentConfig — keys entered after being created
    on Razorpay's own dashboard, not generated by this app).
    """

    class Interval(models.TextChoices):
        MONTHLY = "monthly", "Monthly"
        YEARLY = "yearly", "Yearly"

    tier = models.CharField(max_length=20, choices=SubscriptionTier.choices)
    interval = models.CharField(max_length=10, choices=Interval.choices)
    razorpay_plan_id = models.CharField(max_length=100, unique=True)
    amount_paise = models.PositiveIntegerField(help_text="Amount in paise, not rupees.")

    class Meta:
        unique_together = ("tier", "interval")

    def __str__(self):
        return f"{self.tier} / {self.interval} ({self.razorpay_plan_id})"


class Subscription(models.Model):
    """
    One row per Razorpay subscription a user has created. `status` mirrors
    Razorpay's own subscription status values directly (created / authenticated
    / active / paused / cancelled / completed / expired) rather than inventing
    a parallel vocabulary — keeps webhook handling a straight pass-through.
    """

    # Statuses where a Razorpay mandate is still alive -- either not yet
    # authenticated by the customer, or already collecting. Used by
    # create_user_subscription to decide whether the checkout page should
    # reuse/reject instead of minting a second live mandate for the same
    # user. Plain tuple, matching how `status` itself already mirrors
    # Razorpay's vocabulary directly rather than a parallel enum.
    LIVE_STATUSES = ("created", "authenticated", "active", "paused")

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="subscriptions"
    )
    plan = models.ForeignKey(RazorpayPlan, on_delete=models.PROTECT)
    razorpay_subscription_id = models.CharField(max_length=100, unique=True)
    status = models.CharField(max_length=20, default="created")
    current_period_end = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # Set together when a cancellation/completion webhook lands. Cancelling
    # does NOT downgrade immediately — the user keeps their paid limit for a
    # week (time to actually download anything over the free tier), then
    # gets downgraded, then gets a further 23 days before any file is
    # actually deleted. Both null means "not in a cancellation flow."
    grace_ends_at = models.DateTimeField(
        null=True, blank=True,
        help_text="Downgrade to Free happens after this (7 days post-cancellation).",
    )
    purge_at = models.DateTimeField(
        null=True, blank=True,
        help_text="Files still over the Free limit get deleted after this (30 days post-cancellation).",
    )

    # Dedupe window for the payment.failed notice -- see
    # RazorpaySubscriptionWebhookView.post(). Razorpay redelivers webhooks
    # (retries on any non-2xx, and duplicates land even on a 200); without
    # this, every redelivery of the SAME failure would resend the email.
    # A time window, not a boolean, so it self-resets: a genuinely NEW
    # failure on a later billing cycle is always weeks away, well past any
    # realistic redelivery window, and gets its own notice with nothing
    # needing to explicitly clear a flag first.
    last_payment_failed_notified_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user} -> {self.plan} [{self.status}]"
