# Generated by Django 5.2.8 on 2025-12-22 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('final_path', models.CharField(max_length=1024)),
                ('storage_type', models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], default='local', max_length=10)),
                ('security_mode', models.CharField(choices=[('standard', 'Standard'), ('zero_knowledge', 'Zero Knowledge')], max_length=20)),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterKeyEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enc_master_key_pwd', models.BinaryField()),
                ('kdf_salt', models.BinaryField()),
                ('kdf_memory_kb', models.PositiveIntegerField()),
                ('kdf_iterations', models.PositiveIntegerField()),
                ('kdf_parallelism', models.PositiveIntegerField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_key_envelope', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_file_key', models.BinaryField()),
                ('enc_algo', models.CharField(default='XCHACHA20_POLY1305', max_length=64)),
                ('key_salt_b64', models.CharField(max_length=256)),
                ('nonce_b64', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='files.filerecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'recipient')},
            },
        ),
    ]
