# Generated by Django 5.2.8 on 2026-02-28 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filename_ciphertext', models.BinaryField()),
                ('filename_nonce', models.BinaryField()),
                ('filename_mac', models.BinaryField()),
                ('size', models.BigIntegerField(default=0)),
                ('final_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('manifest_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('storage_type', models.CharField(default='r2', max_length=10)),
                ('security_mode', models.CharField(max_length=20)),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField(blank=True, null=True)),
                ('upload_state', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('committed', 'Committed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('upload_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
