# Generated by Django 5.2.8 on 2026-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filerecord',
            name='files_filer_owner_i_cdd313_idx',
        ),
        migrations.RemoveIndex(
            model_name='filerecord',
            name='files_filer_upload__fe114d_idx',
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='storage_type',
            field=models.CharField(choices=[('r2', 'Cloudflare R2')], default='r2', max_length=10),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='upload_state',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('FINALIZING', 'Finalizing'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20),
        ),
    ]
