# Generated by Django 5.2.8 on 2025-12-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='manifest_path',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
