# Generated by Django 5.2.8 on 2025-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='upload_id',
            field=models.CharField(max_length=64),
        ),
    ]
