# Generated by Django 5.2.8 on 2026-02-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='filename_ciphertext',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='filename_mac',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='filename_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
