# Generated by Django 5.2.8 on 2026-01-02 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filerecord_manifest_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_bytes', models.BigIntegerField(default=1073741824)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='filerecord',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='manifest_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='filerecord',
            index=models.Index(fields=['owner', 'deleted_at'], name='files_filer_owner_i_cdd313_idx'),
        ),
        migrations.AddIndex(
            model_name='filerecord',
            index=models.Index(fields=['upload_id'], name='files_filer_upload__6e78e5_idx'),
        ),
        migrations.AddIndex(
            model_name='filerecord',
            index=models.Index(fields=['created_at'], name='files_filer_created_c3cee8_idx'),
        ),
        migrations.AddField(
            model_name='userquota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userquota',
            index=models.Index(fields=['user'], name='files_userq_user_id_fbc290_idx'),
        ),
    ]
