# Generated by Django 5.2.8 on 2025-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_filerecord_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='upload_id',
            field=models.UUIDField(),
        ),
    ]
