# Generated by Django 5.2.8 on 2026-02-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_filerecord_files_filer_owner_i_cdd313_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='upload_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
