# Generated by Django 5.2.8 on 2026-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_filerecord_upload_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='upload_state',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('FINALIZING', 'Finalizing'), ('COMPLETED', 'Completed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20),
        ),
    ]
