# Generated by Django 5.2.8 on 2026-04-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_filerecord_filename_ciphertext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecord',
            name='upload_id',
        ),
    ]
