# Generated by Django 5.0.4 on 2026-09-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_filerecord_integrity_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='integrity_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='integrity_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='manifest_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
