# Generated by Django 5.2.8 on 2025-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_filechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
