# Generated by Django 5.2.8 on 2025-12-09 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_filerecord_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='final_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
