# Generated by Django 5.2.8 on 2025-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_filerecord_deleted_at_alter_filerecord_final_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='security_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('zero_knowledge', 'Zero Knowledge')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
